### ISSUE TITLE
How to decrypting manually ?

### ISSUE THREAD

**Issue by mavenium** [warpnet/django-nacl-fields#36]
Hello,
How can I decrypt the information encrypted by this library manually ?
Thanks

**Comment by atezet** [comment]
If you got the raw bytes from the database, this script might help:
```
import base64
import nacl.secret

NACL_FIELDS_KEY = b'p1Et2Rb@;^BYdo`ZRFi!Hc-MXu(^|bVqA-FGqffM'
CIPHERTEXT_FROM_DB = b'\x07\x12\xb9C\xed\x93\x05\x04I\x17\x0c)\xc9,+(\x8c:i\x9e6`\x98\xa2\xab\xce\xaa\xb8\x1bC\x8fD`b\x9a\xcf>\xaa\x90V\xfa\x1a\xd598'

nacl.secret.SecretBox(base64.b85decode(NACL_FIELDS_KEY)).decrypt(CIPHERTEXT_FROM_DB)
```
This gives you the decrypted value before it goes into the `to_python` method of the specific field. In the above case `b'False'`
