### ISSUE TITLE
Contributing section in the README

### ISSUE THREAD

**Issue by atezet** [warpnet/django-nacl-fields#41]
A _contributing_ section in the README would be nice. I made a short draft for you:

> ## Contributing
> 
> Start a postgres Docker container for testing using:
> ```
> docker run --rm -e POSTGRES_PASSWORD=postgres POSTGRES_DB=github_actions postgres
> ```
> 
> Then, you can run tests in another window using:
> ```
> virtualenv env
> source env/bin/activate
> pip install '.[test]'
> python manage.py test
> ```
> 
> Before you contribute, make sure you lint your code:
> ```
> pip install '.[lint]'
> flake8 --exclude .git,pycache,docs/conf.py,build,dist,env
> ```
> 
> After your code is done, feel free to open a PR.

**Comment by matthijswendelaar** [comment]
Thanks for the suggestion, we will take a look at it!
