### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tzetter** [warpnet/django-nacl-fields#42]
Would it be possible for you to deploy a new release of the project to pypi? Those of us using Django 4 still has to install the project from git, which isn't ideal.

Thanks!

**Comment by roaldnefs** [comment]
Hi @tzetter, thank you for reminding us! I will create a new release today.

**Comment by roaldnefs** [comment]
The new v4.1.0 is available on PyPi, see: https://pypi.org/project/django-nacl-fields/.
